//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerClient.BeerInventoryGateway {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zfogde.com/wcf/BeerInventoryService", ConfigurationName="BeerInventoryGateway.BeerInventoryService", CallbackContract=typeof(BeerClient.BeerInventoryGateway.BeerInventoryServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface BeerInventoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/JoinParty", ReplyAction="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/JoinPartyResp" +
            "onse")]
        int JoinParty(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/MakeBeerRun", ReplyAction="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/MakeBeerRunRe" +
            "sponse")]
        void MakeBeerRun(string guestName, int numberofBeers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/DrinkBeer", ReplyAction="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/DrinkBeerResp" +
            "onse")]
        void DrinkBeer(string guestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/LeaveParty", ReplyAction="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/LeavePartyRes" +
            "ponse")]
        void LeaveParty(string guestName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BeerInventoryServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/NotifyJoinPar" +
            "ty")]
        void NotifyJoinParty(string guestName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/NotifyBeerCha" +
            "nged")]
        void NotifyBeerChanged(string guestName, int numberofBeers);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.zfogde.com/wcf/BeerInventoryService/BeerInventoryService/NotifyLeavePa" +
            "rty")]
        void NotifyLeaveParty(string guestName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BeerInventoryServiceChannel : BeerClient.BeerInventoryGateway.BeerInventoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BeerInventoryServiceClient : System.ServiceModel.DuplexClientBase<BeerClient.BeerInventoryGateway.BeerInventoryService>, BeerClient.BeerInventoryGateway.BeerInventoryService {
        
        public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BeerInventoryServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int JoinParty(string name) {
            return base.Channel.JoinParty(name);
        }
        
        public void MakeBeerRun(string guestName, int numberofBeers) {
            base.Channel.MakeBeerRun(guestName, numberofBeers);
        }
        
        public void DrinkBeer(string guestName) {
            base.Channel.DrinkBeer(guestName);
        }
        
        public void LeaveParty(string guestName) {
            base.Channel.LeaveParty(guestName);
        }
    }
}
